language: python

matrix:
  fast_finish: true
  include:
    - python: 2.7
    - python: 3.6
    - os: osx
      osx_image: xcode9.3beta
      language: generic

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      # The following wasn't required in the past and therefore may become
      # obsolete once again in the future. Let's wait and see.
      wget https://bootstrap.pypa.io/get-pip.py
      sudo python get-pip.py
      sudo pip install virtualenv
      virtualenv $HOME
      source $HOME/bin/activate
    fi

install:
  - pip install -e .
  - pip install '.[dev]'
  - pip install pytest pytest-cov codecov coveralls


script:
  - py.test --cov=roach
  - python -c 'import roach, sys ; assert "capstone" not in sys.modules'

after_success:
  - codecov
  - coveralls

